# Generated by Django 3.0.4 on 2020-03-09 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=24, unique=True, verbose_name='项目名称')),
                ('pro_ctime', models.DateField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('pro_type', models.CharField(max_length=16, verbose_name='项目类型')),
                ('pro_link', models.URLField(blank=True, verbose_name='link')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '1-项目信息',
                'verbose_name_plural': '1-项目信息',
            },
        ),
        migrations.CreateModel(
            name='UnitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=16, verbose_name='关系名')),
                ('src_unit', models.CharField(max_length=16, verbose_name='源组件')),
                ('src_app', models.CharField(max_length=16, verbose_name='源应用')),
                ('src_port', models.CharField(max_length=16, verbose_name='源端口')),
                ('dest_unit', models.CharField(max_length=16, verbose_name='目的组件')),
                ('dest_vip', models.CharField(max_length=48, verbose_name='组件vip')),
                ('dest_app', models.CharField(max_length=16, verbose_name='目的应用')),
                ('dest_port', models.CharField(max_length=16, verbose_name='目的端口')),
                ('test_way', models.CharField(default='', max_length=200, verbose_name='测试方法')),
                ('note', models.CharField(blank=True, max_length=48, verbose_name='备注')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devices.ProInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '3-组件关系',
                'verbose_name_plural': '3-组件关系',
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=24, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='ip')),
                ('os_name', models.CharField(max_length=16, verbose_name='OS')),
                ('unit_name', models.CharField(max_length=16, verbose_name='组件名')),
                ('nature', models.CharField(help_text='such as 2C4G200G', max_length=16, verbose_name='配置')),
                ('isvhost', models.BooleanField(verbose_name='是否虚拟机')),
                ('hostDevice', models.GenericIPAddressField(verbose_name='宿主机')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devices.ProInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '2-设备信息',
                'verbose_name_plural': '2-设备信息',
            },
        ),
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=16, verbose_name='组件')),
                ('app_name', models.CharField(max_length=24, verbose_name='应用')),
                ('app_user', models.CharField(max_length=24, verbose_name='用户')),
                ('app_passwd', models.CharField(max_length=24, verbose_name='密码')),
                ('start_way', models.CharField(default='', max_length=100, verbose_name='启动方式')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devices.ProInfo', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '4-应用信息',
                'verbose_name_plural': '4-应用信息',
            },
        ),
    ]
