# Generated by Django 3.0.4 on 2020-04-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='hostDevice',
        ),
        migrations.RemoveField(
            model_name='deviceinfo',
            name='unit_name',
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='hostname',
            field=models.CharField(max_length=24, verbose_name='主机简称'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='isvhost',
            field=models.BooleanField(verbose_name='虚机'),
        ),
    ]
