# Generated by Django 3.0.4 on 2020-03-09 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=24, verbose_name='事件名称')),
                ('event_ctime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '2-事件信息',
                'verbose_name_plural': '2-事件信息',
            },
        ),
        migrations.CreateModel(
            name='ProInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=24, unique=True, verbose_name='项目名称')),
                ('pro_ctime', models.DateField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('pro_link', models.URLField(verbose_name='link')),
            ],
            options={
                'verbose_name': '1-项目信息',
                'verbose_name_plural': '1-项目信息',
            },
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=24, verbose_name='任务名称')),
                ('task_status', models.BooleanField(default=False, verbose_name='任务状态')),
                ('task_mtime', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('task_note', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('task_priority', models.PositiveSmallIntegerField(choices=[(0, '高'), (1, '中'), (2, '低'), (3, '不处理')], default=1, verbose_name='优先级')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.EventInfo', verbose_name='所属事件')),
            ],
            options={
                'verbose_name': '3-任务信息',
                'verbose_name_plural': '3-任务信息',
            },
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro.ProInfo', verbose_name='所属项目'),
        ),
    ]
