# Generated by Django 3.0.4 on 2020-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='event_status',
            field=models.BooleanField(default=False, verbose_name='事件状态'),
        ),
    ]
