# Generated by Django 3.0.4 on 2020-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_eventinfo_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proinfo',
            name='pro_status',
            field=models.BooleanField(default=False, verbose_name='任务状态'),
        ),
    ]
