# Generated by Django 3.0.4 on 2020-03-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_proinfo_pro_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='event_note',
            field=models.CharField(default='', max_length=100, verbose_name='备注'),
        ),
    ]
