# Generated by Django 3.0.4 on 2020-03-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_eventinfo_event_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='event_status',
        ),
        migrations.RemoveField(
            model_name='taskinfo',
            name='task_priority',
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='event_priority',
            field=models.PositiveSmallIntegerField(choices=[(0, '高'), (1, '中'), (2, '低'), (3, '已完成'), (4, '不处理')], default=1, verbose_name='优先级'),
        ),
    ]
