# Generated by Django 3.0.4 on 2020-03-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_auto_20200325_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='event_note',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='备注'),
        ),
    ]
