# Generated by Django 3.0.4 on 2020-04-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_proinfo_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='event_note',
        ),
    ]
